In [2]:
import tensorflow as tf
print(tf.__version__)
print(tf.config.list_physical_devices('GPU'))


2.20.0
[]


In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
#sentences
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'im a good boy',
      'im a good developer',
      'understand the meaning of words',
      'your videos are good']

In [5]:
#define the vocabulary size
voc_size=10000

In [6]:
#one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[6576, 3060, 7020, 8115],
 [6576, 3060, 7020, 8448],
 [6576, 7314, 7020, 5599],
 [5148, 3645, 9131, 7495],
 [5148, 3645, 9131, 2990],
 [7181, 6576, 4825, 7020, 9944],
 [8226, 9074, 1636, 9131]]

In [7]:
#word embedding representation


from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import pad_sequences


In [8]:
import numpy as np


In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length )

In [10]:
sent_length = 8



In [11]:
embedded_docs=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)


NameError: name 'onehot_repr' is not defined

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'im a good boy',
    'im a good developer',
    'understand the meaning of words',
    'your videos are good'
]

# Vocabulary size
voc_size = 10000

# One hot representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]

# Sentence length
sent_length = 8

# Padding
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print("One Hot Representation:\n", one_hot_repr)
print("\nPadded Sequences:\n", embedded_docs)


One Hot Representation:
 [[5030, 3843, 3964, 438], [5030, 3843, 3964, 3896], [5030, 7391, 3964, 9706], [4428, 3394, 5462, 4883], [4428, 3394, 5462, 4956], [1716, 5030, 2989, 3964, 9132], [7385, 870, 6609, 5462]]

Padded Sequences:
 [[   0    0    0    0 5030 3843 3964  438]
 [   0    0    0    0 5030 3843 3964 3896]
 [   0    0    0    0 5030 7391 3964 9706]
 [   0    0    0    0 4428 3394 5462 4883]
 [   0    0    0    0 4428 3394 5462 4956]
 [   0    0    0 1716 5030 2989 3964 9132]
 [   0    0    0    0 7385  870 6609 5462]]


In [ ]:
#feature representation 
dim=10

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

In [13]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))  # dim=10 → output_dim=10
model.compile(optimizer='adam', loss='mse')
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6576, 3060, 7020, 8115])

In [20]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step


array([[-0.03718107, -0.03438707, -0.01315325,  0.03640011, -0.03744779,
        -0.01003444, -0.02465246,  0.04079432, -0.00116934,  0.04380847],
       [-0.03718107, -0.03438707, -0.01315325,  0.03640011, -0.03744779,
        -0.01003444, -0.02465246,  0.04079432, -0.00116934,  0.04380847],
       [-0.03718107, -0.03438707, -0.01315325,  0.03640011, -0.03744779,
        -0.01003444, -0.02465246,  0.04079432, -0.00116934,  0.04380847],
       [-0.03718107, -0.03438707, -0.01315325,  0.03640011, -0.03744779,
        -0.01003444, -0.02465246,  0.04079432, -0.00116934,  0.04380847],
       [ 0.02358421,  0.03494655,  0.04839052,  0.04278009,  0.00705037,
         0.02141276, -0.02597066, -0.00304744, -0.02767801,  0.02167602],
       [ 0.00162572,  0.00658501,  0.03997655, -0.01697135, -0.0312331 ,
         0.02414126, -0.01574846,  0.00763673,  0.02791994,  0.02085253],
       [ 0.01798632,  0.03850031,  0.04998961, -0.04489064, -0.03547652,
        -0.04708242, -0.0280565 ,  0.04717592